ipfs_gateways = [
    "http://127.0.0.1:8080/ipfs",
		"https://ipfs.stargaze.zone/ipfs",
    "https://ipfs.io/ipfs",
    # "https://gateway.ipfs.io/ipfs",
    # "https://dweb.link/ipfs",
    # "https://ipfs.fleek.co/ipfs",
    "https://cloudflare-ipfs.com/ipfs",
    # "https://ipfs.eternum.io/ipfs",
    # "https://cf-ipfs.com/ipfs",
]
ipfs_cache_directory = "ipfs"
user_agent = "ipfs-proxy"
connect_timeout = 20000
max_retries = 3
