ipfs_gateways = [
  "https://ipfs.io/ipfs",
  "https://cloudflare-ipfs.com/ipfs",
  # "https://gateway.ipfs.io/ipfs",
  # "https://dweb.link/ipfs",
  # "https://ipfs.fleek.co/ipfs",
  # "https://ipfs.eternum.io/ipfs",
  # "https://cf-ipfs.com/ipfs",
]
ipfs_cache_directory = "ipfs"
user_agent = "ipfs-proxy https://github.com/penso/ipfs-proxy"
connect_timeout = 20000
pause_gateway_seconds = 120
delete_after_days = 5
max_content_length = 104857600 # 100MB
server_port = 3490
db_max_connections = 100
db_min_connections = 10

[ipfs]
binary_path = "ipfs"
enabled = false

[[permitted_resize_dimensions]]
width = 100
height = 100
