ipfs_gateways = [
  "https://ipfs.io/ipfs",
  "https://cloudflare-ipfs.com/ipfs",
  # "https://gateway.ipfs.io/ipfs",
  # "https://dweb.link/ipfs",
  # "https://ipfs.fleek.co/ipfs",
  # "https://ipfs.eternum.io/ipfs",
  # "https://cf-ipfs.com/ipfs",
]
ipfs_cache_directory = "ipfs"
user_agent = "ipfs-proxy https://github.com/penso/ipfs-proxy"
connect_timeout = 20000
max_retries = 3
pause_gateway_seconds = 120
delete_after_days = 5
max_content_length = 104857600 # 100MB
server_port = 3490
